### ISSUE TITLE
status: Denied

### ISSUE THREAD

**Issue by bonuzzz** [koshev-msk/luci-app-modeminfo#14]
Hi
I have status: denied. I have quectel ep06. 3ginfo shows status properly.

**Comment by koshev-msk** [comment]
Please show output gcom-script to analyze the error.
gcom -d /dev/your_ttyUSB_port -s /usr/share/modeminfo/scripts/3ginfo > /path/to/output.log
Thannks.

**Comment by bonuzzz** [comment]
+CSQ: 31,99
+COPS: 0,2,"25011",7
+QCSQ: "LTE",52,-83,207,-14
+QNWINFO: "FDD LTE","25011","LTE BAND 3",1602
+QTEMP: 31,28,28
+CREG: 2,3
+CGREG: 2,1,"2616","DDAEA01",7
+CEREG: 2,1,"2616","DDAEA01",7
DEVICE:Quectel EP06
IMEI:

**Comment by koshev-msk** [comment]
I checked it. On AT-command service manual page 74/75 Quectel EP06, in AT+CREG command, must return code 1 or 5 for home mobile network or roaming state. Please check "state" on another sim-card.

**Comment by koshev-msk** [comment]
Fixed in https://github.com/koshev-msk/luci-app-modeminfo/commit/886e161d483807b2887ad90b0ecdf106b961a740
