### ISSUE TITLE
Abnormal data from Fibocom L850-L860 modems

### ISSUE THREAD

**Issue by Harwesta** [koshev-msk/luci-app-modeminfo#16]
Please add a Fibocom family section in modeminfo script.

For these models apply sequence in "GENERIC" script sections, but Fibocom uses a differents commands for get some data:
1. For model ID:
AT+GMM?
response
+GMM: "L850 LTE Module","L850" (or "L860 LTE Module","L860" )

2. For temperature:
AT+MTSM=2,10 (setup to read temperature each 10 seconds) - run once
AT+MTSM? - Read data
response
+MTSM: 35

3. For current bands, aggregations and bandwidtch:
AT+XLEC?
response
+XLEC: 0,2,3,3,BAND_LTE_7
           0 Disable URC
              0 - not on LTE, 1 - Primary cell only, 2...5 - Secondary cells added
		 0 - 1.4MHz, 1 - 3MHz, 2 - 5MHz, 3 - 10MHz, 4 - 15MHz, 5 - 20MHz, 255 - Invalid
		   0 - 1.4MHz, 1 - 3MHz, 2 - 5MHz, 3 - 10MHz, 4 - 15MHz, 5 - 20MHz, 255 - Invalid

And optional - Power supply voltage
AT+CBC
response
+CBC: 0,3750
          0 - battery (not use)
            3750 - voltage in mV

See screenshot 
![modeminfo](https://user-images.githubusercontent.com/65107625/112096500-34c15800-8bc0-11eb-8f61-414fa2cf1a69.jpg)

Tnx

**Comment by koshev-msk** [comment]
Hi! Thanks for your issue!
So, for fully information needs next values:
1. Channel nubmer for LTE (primary cell) and WCDMA/3G networks.
2. SINR or EcIO for LTE and WCDMA/3G.
3. RSRQ value for LTE network.
4. Separated values for each band LTE aggregation. E.g. PCC: b1; SCC1: b3; SCC1: b7

**Comment by Harwesta** [comment]
Ok!

**1. For channel number:**
AT+XADPCLKFREQINFO=01 - set command enables/disables the +XADPCLKFREQINFO- run once
response
+XFREQINFO: 2675000000, 3, -12, -5675; 2555000000, 10000000, 0, 0; 2675000000, 10000000, 0, 0; 1872900000, 10000000, 0, 0
Legend: 
First number is a center frequency of the channel number in Hz, should be zero when the radio is off.
Second number is a frequency spread of the channel number in Hz, should be zero when the radio is off.
_In my case "3" is abnormal data, it must be 10000000 (10MHz)._
Third number is a noise power referred at antenna in dBm, at the reported center frequency, and integrated over a bandwidth equal to reported frequency spread. This value shall be zeroed if not used.
Four number - i don't known :)

**2. For SINR and EcIO** - i think this option use fro EVDO mode only, see below:
AT+XCESQ?
response
+XCESQ: 0,99,99,255,255,0,46,-20
Legend: <n>,<rxlev>,<ber>,<rscp>,<ecno>,<rsrq>,<rsrp>,<rssnr>,<1xrtt_rssi>,<1xrtt_ecio>,
<evdo_rssi>,<evdo_sinr>

**3. For RSRQ and RSCP:**
AT+CESQ
response
+CESQ: 99,99,255,255,0,46
Legend: <rxlev>, <ber>, <rscp>, <ecno>, <rsrq>, <rsrp>
RSCP levels
0= < -120dbm
1= -120 dBm ... -119 dBm
2= -119 dBm ... -118 dBm
/.../
94= -27 dBm ... -26 dBm
95= -26 dBm ... -25 dBm
96= >25 dBm 
255= not known or not detectable

RSRQ levels
0= < -19.5 dB
1= -19.5 dB ... -19 dB
2= -19 dB ... -18.5 dB
/.../
32= -4 dB ... -3.5 dB
33= -3.5 dB ...-3 dB
34= >-3 dB 
255= not known or not detectable

4. No detailed information.

In addition, you can use a Measured Cell Information command:
AT+XMCI=1
Response (two string, first is serving cell, second is neighboring cell)
+XMCI: 4,250,99,"0x65D2","0x0A18C504","0x0126","0x00000CE4","0x00005334","0xFFFFFFFF",49,4,-12,"0x00000000","0x00000000"
+XMCI: 5,000,000,"0xFFFE","0xFFFFFFFF","0x0003","0x00000757","0xFFFFFFFF","0xFFFFFFFF",54,8,255,"0x7FFFFFFF","0x00000000"

Legend: <TYPE>,<MCC>,<MNC>,<LAC>,<CI>,<BSIC>,<RXLEV>,<BER>,<ARFCN>,<TARELIABILITY>,<TA>
<Type>.
0= GSM serving cell
1= GSM neighboring cell
2= UMTS serving cell
3= UMTS neighboring cell
4= LTE Serving Cell
5= LTE Neighboring cell
6= 1xRTT Serving Cell
7= 1xRTT Neighboring cell
8= EvDO Serving Cell
9= EvDO Neighboring cell

**Comment by Harwesta** [comment]
Find & try next command (omitted in AT command user guide)

AT+RSRP?
Result
+RSRP: 457,3300,-93.00,197,1879,-94.00,294,3300,-92.00

And 

AT+RSRQ?
Result
+RSRQ: 457,3300,-18.50,294,3300,-18.00,58,1879,-16.00

**Comment by koshev-msk** [comment]
Amazing! RSRQ and RSCP commands showing EARCN cnannels.
What answered next AT-commands?
AT+GTCAINFO?
AT+GTCCINFO?
AT+GTRAT?

**Comment by Harwesta** [comment]
Of the listed commands, only the first is in the list, AT+GTCAINFO.
This command is omitted in AT command user guide.
Device is in the office now, I can see answers on Monday.

**Comment by 5gsystems** [comment]
AT+GTMCFWVER?
+GTMCFWVER: "18600.5001.00.35.01.57"
OK

AT+GTCAINFO?
ERROR

AT+GTCCINFO?
ERROR

AT+GTRAT?
ERROR

**Comment by Harwesta** [comment]
Done...
AT+GTCAINFO?
Answer
+GTCAINFO: 2
+GTCAINFO: 1,3,250,99,26066,169395463,3,52,11,-6,1879,19879,3,3
+GTCAINFO: 2,7,294,50,9,-6,3300,19879,3,255
OK

Commands "AT+GTCCINFO?" & "AT+GTRAT?" answers "+CME ERROR: 4"

**Comment by koshev-msk** [comment]
Support add in https://github.com/koshev-msk/luci-app-modeminfo/commit/e5db86cc1c1b9d5f8031e7e9236b67dd5a1fe838

**Comment by koshev-msk** [comment]
Closed due to long inactivity.
