### ISSUE TITLE
Please add mcc & mnc for Indonesian operators

### ISSUE THREAD

**Issue by conc123** [koshev-msk/luci-app-modeminfo#20]
Please add mcc & mnc for Indonesian operators

51000;PSN
51001;Indosat Ooredoo
51009;Smartfren
51010;Telkomsel
51011;XL
51027;Net 1
51078;Hinet
51089;3

**Comment by koshev-msk** [comment]
Added in https://github.com/koshev-msk/luci-app-modeminfo/commit/40be283e6f2f75ae1f996d549709fc9e97f3671c
