### ISSUE TITLE
Error compile or source 'luci-app-modeminfo'

### ISSUE THREAD

**Issue by anhnqt** [koshev-msk/luci-app-modeminfo#24]
1. I have 2 ipk file:
- (1) One from you (https://inf.labz.ru/repo/)
- (2) One from your source compile

2. The same setup both 2 case:
![image](https://user-images.githubusercontent.com/28293587/124530177-34c72a00-de36-11eb-8609-ce8a10f4700f.png)

3. When I use (1), the software can work:

- Good data

![image](https://user-images.githubusercontent.com/28293587/124530083-0a756c80-de36-11eb-89a7-07d6b1943962.png)

4. When I install ipk file from (2), the software cant show information of QMI module:
- No data to see
![image](https://user-images.githubusercontent.com/28293587/124530844-760c0980-de37-11eb-95d8-b8fe7fc46fa2.png)

- This is systemlog can check:
![image](https://user-images.githubusercontent.com/28293587/124530224-50323500-de36-11eb-931e-610ffb48a96f.png)

Have any recommend for me?
Thanks

**Comment by Harwesta** [comment]
Hi!
I think is incorrect permission for modeminfo module.
Check it and set to chmod 755

**Comment by anhnqt** [comment]
Hi @Harwesta 
Ok now with chmod 755 /usr/bin/modeminfo
![image](https://user-images.githubusercontent.com/28293587/124535915-2af6f400-de41-11eb-9670-963e83117bb6.png)

How I can add permission for modeminfo module in your source code, and user no need to set permission?

Many thanks;

**Comment by Harwesta** [comment]
Please wait a answer from maintainer.
I hawe a same problems with luci-app-atinout module and write this solution.

**Comment by koshev-msk** [comment]
The Permissions are right. Check you router filesystem.
