### ISSUE TITLE
Error in the RSSI calculation after 18-JUL-21 update 

### ISSUE THREAD

**Issue by Harwesta** [koshev-msk/luci-app-modeminfo#26]
After last updates on 18-JUL-21 with comment "modeminfo: Fix Intel XMM RSSI value [2]" i see very low rates of RSSI.
Before this change it was RSSI=75dBm and Signal strength: 63%.
After it became 109dBm and 6%, in same place.
I think error in the RSSI calculation formula.

Modem Fibocom L850GL
Openwrt-21.02 branch (git-21.106.55967-06dd6b5) / OpenWrt 21.02.0-rc1 r16046-59980f7aaf

**Comment by koshev-msk** [comment]
The modem have source incorrect data. 
Previous value RSSI=RSRP-RSRQ same incorrect. Attempts find a solution to be continue.

**Comment by Harwesta** [comment]
I rollback this string to preview state:
		INTEL) CSQ=$(echo "$O" | awk -F[,\ ] '/^\+CSQ/ {print $**2**}') ;;

in /usr/share/modeminfo/scripts/modeminfo script.
Signal strength values have increased to RSSI=91dBm and Signal strange to 35%, but have not reached their previous normal state.
I assume that RSSI=75dBm and Signal strength: 63% was realistic and correct in my location.

**Comment by koshev-msk** [comment]
The data very strange format. 
In 3GPP specification 27.007 §8.5+CSQ will next output format.
```+CSQ: <rssi>,<ber>```
Where is rssi range 0-31 and ber range 0-7. But modem sent data:
```
at+csq=?
+CSQ: (0-31,99),(0-7,99)

OK
at+csq?
+CSQ: 11,26

OK
```
Second value out of range in answer.
The modem have proiperitary alternative command +XCESQ in FIBOCOM L860 AT Commands User Manual Version: V3.2.3 §9.1.19
```
at+xcesq=?
+XCESQ: (0,1),(0-63,99),(0-7,99),(0-96,255),(0-49,255),(0-34,255),(0-97,255),(-100-100,255),(0-90,255),(0-62,255), (0-90,255), (0-60,255)

OK
```
Where second value range 0-63 is RSSI value, but modem send 99 - no data.

```
at+xcesq?
+XCESQ: 0,99,99,255,255,17,49,43,255,255,255,255

OK

```

**Comment by koshev-msk** [comment]
Try last commit https://github.com/koshev-msk/luci-app-modeminfo/commit/09488dda3eca7969c0b4688a5352f2d1368bae5a

**Comment by Harwesta** [comment]
All fine!
RSSI and Signal quality same as reality
![modeminfo](https://user-images.githubusercontent.com/65107625/126313574-5473f3b3-e96d-48d7-80c1-597616dd136d.jpg)
