### ISSUE TITLE
Неверное значение SINR для Qualcomm модемов.

### ISSUE THREAD

**Issue by OdinokijKot** [koshev-msk/luci-app-modeminfo#27]
https://github.com/koshev-msk/luci-app-modeminfo/blob/cb05a231fe9219e816141cbd9d69895eeebe4c3a/root/usr/share/modeminfo/scripts/modeminfo#L472

В этом месте баг! Команда ^RFSTS выдаёт значение SINR не в db, а в условных единицах от 0 до 250. Для того, что бы перевести в db нужно вычесть постоянное смещение. Значение смещения можно получить сравнив вывод ^DEBUG и ^RFSTS. Либо получать SINR из команды ^DEBUG, аналогично тому, как это сделано для Dell DW5821.

Возможно аналогичная проблема в получении значения SINR для не LTE режима. 
Вообще не понятно откуда берётся значение SINR для WCDMA режима. 
Вот тут https://github.com/koshev-msk/luci-app-modeminfo/blob/cb05a231fe9219e816141cbd9d69895eeebe4c3a/root/usr/share/modeminfo/scripts/modeminfo#L496
берём SINR из EcIo, но это не соотношение сигнал\шум, а мощность передатчика в dBm.
"<Ec/Io> -31…0 Active Ec/Io(chip energy per total wideband power in dBm)" - цитата из мануала по ат-коммандам на LN940 186 страница.
[HP_lt4220(telit_ln940)_at_commands.pdf](https://github.com/koshev-msk/luci-app-modeminfo/files/6853537/HP_lt4220.telit_ln940._at_commands.pdf)

**Comment by koshev-msk** [comment]
> Команда ^RFSTS выдаёт значение SINR не в db, а в условных единицах от 0 до 250.

No! The last value show be in dB.
```
^RFSTS:
"25020",1875,-85.8,-58.1,-11.5,9202,0,0,19,1,433,"250207422593290","Tele2",3,3,13.7
```
13.7 not be correct range of 0...250

> из команды ^DEBUG
AT^DEBUG send incorrect RS-SINR value.

> SINR=$ECIO

Is just variable name. Ec/Io value
https://github.com/koshev-msk/luci-app-modeminfo/blob/cb05a231fe9219e816141cbd9d69895eeebe4c3a/root/usr/share/modeminfo/scripts/modeminfo#L494

Closed.

**Comment by OdinokijKot** [comment]
> Value 13.7 is not correct range of 0...250 

А почему Вы решили, что 13.7 не входит в диапазон [0,250]? Значения вполне может быть дробным, так же как и значение RS-SINR в ^DEBUG.
SINR может быть отрицательным, это происходит, когда шума в канале больше чем полезного сигнала, но в ^RFSTS он начинается с 0 и никогда не бывает отрицательным. 
Почему Вы решили, что в ^DEBUG отображается некорректное значение RS-SINR?
Мне кажется смещение там в районе 10 единиц. На грани разрыва соединения у меня ^DEBUG показывал -10 dB, при этом в ^RFSTS был 0.0 . Отловить это в терминале не успел, успел просто поймать плохой сигнал с отрицательным SINR:

```
ati
Manufacturer: QUALCOMM INCORPORATED
Model: 4105
Revision: T77W676.F0.0.0.4.7.GC.017  1  [Jul 11 2018 00:00:00]
SVN: 03
IMEI: XXXXXXXXXXXXXXX
+GCAP: +CGSM,+DS,+ES

OK

AT^RFSTS?
^RFSTS:
"25020",3400,-100.2,-69.1,-14.6,XXXXX,180,0,19,1,XXX,"XXXXXXXXXXXXXXX","ROSTELECOM",3,7,8.2

OK

AT^DEBUG?

EARFCN(DL/UL): 3400/21400
BAND: 7
BW: 10.0 MHz
PLMN: 250 00
TAC: XXXXX
eNB ID(PCI): XXXXXX-X(XXX)
ESM CAUSE: 0
EMM CAUSE: -1
DRX: 1280ms
RSRP: -100.9dBm
RSRQ: -20.0dB
RSSI: -63.1dBm
L2W:  0
RI: 1
CQI:  8
RS-SINR: -3dB
STATUS: SRV/REGISTERED
SUB STATUS: NORMAL_SERVICE
RRC Status: CONNECTED
SVC: CS_PS
Tx Pwr: 20.0dB
TMSI: XXXXXXXXXXX
IP: 100.78.160.102
AVG RSRP: -100.9dBm

OK
```

**Comment by koshev-msk** [comment]
Мануалы пишут одни люди, прошивки пишут другие люди. Не всегда мануал соответствует действительности.
Мы знаем что значение SINR от -20 до +30 дБ. Из мануала знаем, что значение от 0 до 250. Покажите мне это значение из RFSTS больше 50 или 100.
Ваша формула расчета?

**Comment by koshev-msk** [comment]
После того, как Вы посчитаете, предлагаю сравнить результат с другими модемами на том же АФУ.

**Comment by OdinokijKot** [comment]
> Мануалы пишут одни люди, прошивки пишут другие люди. Не всегда мануал соответствует действительности.

Согласен, везде бывают странности и ошибки.

> Мы знаем что значение SINR от -20 до +30 дБ. 

Да, но в RFSTS я ни разу не встречал отрицательных значений. Не обязательно, что весь диапазон от 0 до 250 используется.

> После того, как Вы посчитаете, предлагаю сравнить результат с другими модемами на том же АФУ.

Проверю обязательно на тех же антеннах L860-GL и сообщу о результате.
А почему DEBUG изпользуется в Dell DW5821?

> Ваша формула расчета?

Пока склоняюсь к смещению в -10, но сдаётся мне, что там может быть более сложная математика.
Пробовал сравнивать значения выдаваемые в RFSTS и DEBUG с значениями из uqmi. По RSRP, RSRQ, RSSI всё везде сходится, а вот с sinr какая-то чеуха. uqmi может показать и -30 и +30 и вообще погоду на марсе, но когда значения кажутся адекватными, то они близки к значению из DEBUG.
О, я знаю что можно использовать как эталон. У Qualcomm же есть служебная утилита мониторинга сети, попробую сравнить её показания с выдачей терминала.

**Comment by koshev-msk** [comment]
> RFSTS я ни разу не встречал отрицательных значений.

А я встречал. Предъявить смогу только осенью, пока прибор стоит там, где SINR строго положительный.

> L860-GL

Не пойдёт. У него с показаниями еще хуже. Возьмите что-то из Huawei или Quectel.

> Не обязательно, что весь диапазон от 0 до 250 используется.

Обязательно весь. Иначе какой смысл в нём? 0 соответсвует - 20дБ, 250 — +30дБ.  

> uqmi может показать

Это не SINR, а RSSNR.

Оставлю пока закрытым.

**Comment by OdinokijKot** [comment]
> Обязательно весь. Иначе какой смысл в нём? 0 соответсвует -20дБ, 250 — +30дБ.

Во! И я про то же. То есть это значение, как минимум должно нормироваться под этот диапазон, и только потом попадать в вебморду. Как вариант по такой формуле (N/5)-20 , но это линейное нормирование, скорее всего оно не подойдёт, может быть нужно какое-нибудь логорифмическое, так как db логорифмические единицы.
В общем разбирусь с qxdm и покажу результаты сравнения, думаю уж он то правильно будет всё показывать. Тогда уже будет смысл гадать о формуле перевода.

> Это не SINR, а RSSNR.

В смысле uqmi показывает не sinr, или sinr и rs-sinr разные параметры? Тут я не компетентен, просветите меня. Я думал это одно и то же. Везде пишут просто sinr, даже в родных мануалах, я посчитал это одним и тем же параметром.

**Comment by koshev-msk** [comment]
> должно

После того как Вы увидите значения больше 50, а лучше больше ста.

> просветите меня

https://www.sharetechnote.com/html/RF_Handbook_SNR.html
В кратце тут. 
Прололжить лучше на 4pda, напишите мне, в QMS. Через сутки оффтоп потру.

**Comment by koshev-msk** [comment]
В общем этот вопрос я задал в telit.
И получил следующее:
SINR defines​
> /**< Logarithmic value of SINR. Values are in 1/5th of a dB.
Range: 0 to 250, which translates to -20 dB to +30 dB. */ on QC document.
In the meanwhile it is so strange why your SINR value indicated 12.6 (fractional number).

В сухом остатке:
1. Диапазон SINR 0-250 должен быть целым числом.
2. Формула расчёта линейная (N/5)-20.

Ошибка налицо.
Дальше мне было предложено заполнить кучу документов, от чего я веждливо отказался.

**Comment by OdinokijKot** [comment]
Ну вот. Чудеса, оказывается самое первое "наивное" предположение получилось верным. 
А у DW5821 случае не так же считается? Там вроде тоже куаллком. Сейчас оно берётся из вывода дебага.
У меня с qxdm пока ничего не вышло. С ходу он диаг-порт модема не увидел. А больше времени не было заниматься пока.

**Comment by koshev-msk** [comment]
> А у DW5821 случае не так же считается?

Такие данные у модема есть только в DEBUG.
Аналогов RFSTS у него нет.
