### ISSUE TITLE
Network Band and Temp not detected

### ISSUE THREAD

**Issue by AZBoxEmperador** [koshev-msk/luci-app-modeminfo#31]
Network band and the Temperature is not being detected with a Sierra Wireless EM7565

![image](https://user-images.githubusercontent.com/4449023/131911778-d4243321-8ec5-49a3-aee5-b727677dcdae.png)

**Comment by koshev-msk** [comment]
Hi! This modem not support currently yet.  For more details send generated file /tmp/sierra.log from next command:
```gcom -d /dev/ttyUSB_X_ -s /usr/share/modeminfo/scripts/3ginfo.gcom > /tmp/sierra.log```
where _X_ serial port number for answer at commands (see config of modeminfo)
Probably, more information will be needed.

**Comment by koshev-msk** [comment]
Who network bands use ISP from your region?

**Comment by AZBoxEmperador** [comment]
this is what i get: **Can't open device /dev/ttyUSB1.**

tested all available ports that I can think of

![image](https://user-images.githubusercontent.com/4449023/132025398-215a65a3-cf44-4109-99f0-aa8549b9a731.png)

**Comment by AZBoxEmperador** [comment]
if I run this command **ls -a /dev** I get 

![image](https://user-images.githubusercontent.com/4449023/132042348-4c8ca5e2-b643-4843-a605-14d9327edcf7.png)

ruuning this **dmesg | grep usb**  I get:

![image](https://user-images.githubusercontent.com/4449023/132042425-b7ae3a1a-6c45-496d-a29c-ee8b5cc90e9d.png)

and with **lsusb**
![image](https://user-images.githubusercontent.com/4449023/132042534-8332b974-8625-44f3-b2b4-213583eaecfe.png)

**Comment by AZBoxEmperador** [comment]
LTE bands are: B2, B4 and B28. These are the bands we use here.

Is it possible to add a tab for AT commands in the future?

Thanks

**Comment by koshev-msk** [comment]
I added Bands 2,4,28. Try last commit.
AT terminal live here https://github.com/koshev-msk/luci-app-atinout/tree/rafal

**Comment by koshev-msk** [comment]
Closed due to long inactivity.
