### ISSUE TITLE
Commit 558ff93 (#32 by csharper2005) messed up the work with the L850GL modem

### ISSUE THREAD

**Issue by Harwesta** [koshev-msk/luci-app-modeminfo#33]
Сommit 558ff93 messed up the work with the L850GL modem: all status data on "Modeminfo: Signal Overview" tab is missing.

**Comment by koshev-msk** [comment]
Need details. Work with L860-GL

**Comment by Harwesta** [comment]
What information is required?
After enabling this patch, absolutely all data from the page 'modeminfo' disappeared.

**Comment by Harwesta** [comment]
After last commit i rebuild new firmware, modeminfo module works fine.
