### ISSUE TITLE
Multiple modems always ends up on wdm1

### ISSUE THREAD

**Issue by spacesuitdiver** [koshev-msk/luci-app-modeminfo#37]
I have two modems but I am only able to read the last modem in the list using qmi mode. Saving in LuCI always has the selection at the end after visiting Setup tab again. 

Aside, I can only read the device name in non-qmi but I haven’t researched this problem yet and can make a separate ticket.

**Comment by koshev-msk** [comment]
Fixed in https://github.com/koshev-msk/luci-app-modeminfo/commit/e8774db55cfea8322601dd679050d751776b0028

**Comment by koshev-msk** [comment]
Closed due to inactivity.
