### ISSUE TITLE
telit ln960 / dell DW5821e

### ISSUE THREAD

**Issue by vlw** [koshev-msk/luci-app-modeminfo#40]
Does not work
![image](https://user-images.githubusercontent.com/6003820/147861889-819875d2-2bd1-4595-861c-47a92503312a.png)
![image](https://user-images.githubusercontent.com/6003820/147861898-56beaab3-dba0-4afd-9ea0-4e115fefdbd8.png)

**Comment by vlw** [comment]
![image](https://user-images.githubusercontent.com/6003820/147861942-d60ddc47-5f5e-4743-8ea6-66054ad3de78.png)
![image](https://user-images.githubusercontent.com/6003820/147861968-9c4173f6-47cc-4c2a-a04c-8dbf5db94235.png)

**Comment by koshev-msk** [comment]
Install qmi-utils package.

**Comment by vlw** [comment]
this package already installed. I found reason: it is flag -p. If I remove it from script, all works

![image](https://user-images.githubusercontent.com/6003820/147870947-2533a3f0-676c-4b6b-bea6-df616a52cc2c.png)

**Comment by vlw** [comment]
@koshev-msk please re-open issue, it is not fixed

**Comment by Harwesta** [comment]
@vlw 
This this not bug.
"-p" flag needs for proxy-mode (AT over qmi)

**Comment by vlw** [comment]
> @vlw This this not bug. "-p" flag needs for proxy-mode (AT over qmi)

looks like not all modems support proxy mode

**Comment by koshev-msk** [comment]
* modeminfo-qmi: optional enable qmi-proxy mode koshev-msk@d3e0a1742d64aa9d72dbcfebc06577b4cac31773

**Comment by koshev-msk** [comment]
Closed due to inactivity.
